import { useEffect, useRef, useState } from "react";
import type { ReactNode } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "../../components/common/Button";
import { Card } from "../../components/common/Card";
import { Timer } from "../../components/common/Timer";
import type { GameComponentProps } from "../registry";
import { resources, type IslandPublic, type IslandPrivate, type Resource } from "./types";
import { IslandMap } from "./IslandMap";
import { TruthReveal } from "./TruthReveal";
const phases = { DAY_START: "รุ่งเช้า", DAY: "กลางวัน", NIGHT: "กลางคืน", MORNING: "รายงานยามเช้า", DISCUSSION: "พูดคุยก่อนโหวต", VOTE: "โหวตผู้ต้องสงสัย", VOTE_RESULT: "ผลโหวต", ESCAPE: "เดินทางไปชายหาดเพื่อหนี", FINISHED: "จบเกมแล้ว" };
const cls = "min-w-0 rounded-lg border border-slate-700 bg-slate-900 p-2 text-sm text-white";
function Popup({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { ref.current?.showModal(); return () => ref.current?.close(); }, []);
  return <dialog ref={ref} onCancel={e => { e.preventDefault(); onClose(); }} className="max-h-[85vh] w-[min(94vw,34rem)] overflow-y-auto rounded-2xl border border-slate-700 bg-slate-950 p-6 text-white backdrop:bg-black/75"><div className="mb-5 flex justify-between gap-4"><h2 className="text-xl font-semibold">{title}</h2><button autoFocus aria-label="ปิดหน้าต่าง" className="rounded-lg px-3 text-xl hover:bg-slate-800" onClick={onClose}>×</button></div>{children}</dialog>;
}
export function IslandBetrayalGame({ room, publicState, privateState, selfUserId, onAction }: GameComponentProps) {
  const s = publicState as IslandPublic | null, mine = privateState as IslandPrivate | null;
  const navigate = useNavigate();
  const [error, setError] = useState(""), [busy, setBusy] = useState(false), [selected, setSelected] = useState<string | null>(null);
  const [text, setText] = useState(""), [target, setTarget] = useState("");
  const [give, setGive] = useState<Resource>("food"), [want, setWant] = useState<Resource>("water");
  const [quantity, setQuantity] = useState(1), [wantQuantity, setWantQuantity] = useState(1);
  const [showRole, setShowRole] = useState(false), [vote, setVote] = useState(""), [showVote, setShowVote] = useState(false);
  const [alertText, setAlertText] = useState<string | null>(null), [killTarget, setKillTarget] = useState<string | null>(null);
  const evidenceCount = useRef(0);
  useEffect(() => { setShowVote(s?.phase === "VOTE"); setVote(""); setError(""); }, [s?.phase, s?.day, s?.votedUserIds.length === 0]);
  useEffect(() => { const newEvidence = mine?.evidence.slice(evidenceCount.current) ?? []; evidenceCount.current = mine?.evidence.length ?? 0; const alert = newEvidence.find(e => e.includes("🚨") || e.includes("⚠️")); if (alert) setAlertText(alert); }, [mine?.evidence.length]);
  async function act(type: string, payload: unknown = {}) {
    if (busy) return false; setBusy(true); setError("");
    try { const r = await onAction(`island:${type}`, payload); if (!r.ok) setError(r.error ?? "ทำรายการไม่สำเร็จ"); return r.ok; }
    catch { setError("การเชื่อมต่อขัดข้อง กรุณาลองใหม่"); return false; } finally { setBusy(false); }
  }
  if (!s || !mine || !s.world) return <Card className="mx-auto mt-8 max-w-xl">กำลังโหลดข้อมูลเกาะ…</Card>;
  const self = s.players.find(p => p.userId === selfUserId);
  const active = mine.alive && Boolean(self?.connected), mobile = active && ["DAY", "NIGHT", "ESCAPE"].includes(s.phase) && !busy;
  const day = active && s.phase === "DAY" && !busy, location = mine.myLocation;
  const chosen = selected && s.world[selected] ? selected : location;
  const area = s.world[chosen], here = s.world[location];
  const route = s.routes.find(r => r.from === location && r.to === chosen || r.to === location && r.from === chosen);
  const name = (id: string) => s.players.find(p => p.userId === id)?.username ?? id;
  const selectResource = (r: Resource, setter: (r: Resource) => void, label: string) => <select aria-label={label} className={cls} value={r} onChange={e => setter(e.target.value as Resource)}>{Object.entries(resources).map(([r,label]) => <option key={r} value={r}>{label}</option>)}</select>;
  const progress = (label: string, n: number, total: number) => <div><div className="flex justify-between gap-2 text-sm"><span>{label}</span><span>{n}/{total}</span></div><progress aria-label={label} max={total} value={n} className="h-2 w-full accent-emerald-500"/></div>;
  if (s.phase === "FINISHED" && s.result) return <main className="mx-auto max-w-5xl p-4 sm:p-8"><Card><TruthReveal result={s.result}/><Button className="mt-6" variant="secondary" onClick={() => navigate(`/lobby/${room.roomCode}`)}>กลับไปที่ล็อบบี้</Button></Card></main>;
  return <main className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6">
    <Card className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs tracking-widest text-emerald-400">{room.roomName} · วันที่ {s.day}/{s.rules.maxDays}</p><h1 className="mt-1 text-2xl font-semibold">Island Betrayal</h1><p className="mt-1 text-sm text-slate-400">{phases[s.phase]} · {s.weather}</p></div><Timer endsAt={s.phaseEndsAt}/></Card>
    {!active && <p className="rounded-xl border border-amber-800 bg-amber-950/40 p-4 text-amber-200">{!mine.alive ? "คุณเสียชีวิตแล้ว — รับชมแผนที่ แชต และบันทึกสาธารณะได้จนจบ" : "คุณออกจากเกมอยู่ กรุณากลับเข้าห้อง"}</p>}
    {error && <p role="alert" className="rounded-xl bg-red-950 p-3 text-red-200">{error}</p>}
    {s.phase === "NIGHT" && <p className="rounded-xl border border-indigo-800 bg-indigo-950/50 p-4 text-sm text-indigo-200">กลางคืนยาว {s.rules.cycleSeconds} วินาทีเท่ากลางวัน · กลับแคมป์ตามเส้นทางหรืออยู่ข้างนอกได้ · จุดผู้เล่นบนแผนที่เป็นตำแหน่งก่อนค่ำ คุณเห็นตำแหน่งตัวเองจริง</p>}
    {s.phase === "DISCUSSION" && <Card><h2 className="font-semibold">พูดคุยก่อนโหวต</h2><p className="mt-2 text-sm text-slate-400">เปรียบเทียบคำบอกเล่าและรายงานยามเช้าในแชต ต่อให้กำจัด Spy หมดก็ยังต้องทำภารกิจและหนีจากเกาะ</p></Card>}
    {s.phase === "VOTE" && <Card><p className="mb-3 text-sm">ลงคะแนนแล้ว {s.votedUserIds.length} คน · 1 สิทธิ์ต่อผู้มีชีวิต</p><Button disabled={!active} onClick={() => setShowVote(true)}>{mine.votedFor ? `คุณโหวต ${name(mine.votedFor)} แล้ว` : "โหวตผู้ต้องสงสัย"}</Button></Card>}
    {s.voteResult && <Card><h2 className="font-semibold">ผลโหวต</h2><div className="mt-3 space-y-2">{Object.entries(s.voteResult.counts).map(([id,n]) => <div key={id}>{progress(name(id),n,Math.max(1,s.players.filter(p=>p.alive).length+1))}</div>)}</div><p className="mt-3 text-amber-300">{s.voteResult.eliminated ? `${name(s.voteResult.eliminated)} ถูกกำจัด${s.voteResult.role ? ` · ${s.voteResult.role}` : ""}` : s.voteResult.tied ? "คะแนนเสมอ" : "ไม่มีผู้ถูกกำจัด"}</p></Card>}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_19rem]">
      <div className="space-y-5">
        <IslandMap state={s} location={location} onSelect={setSelected}/>
        <Card><h2 className="text-lg font-semibold">{area.name}{chosen === location ? " · คุณอยู่ที่นี่" : ""}</h2><p className="mt-1 text-sm text-slate-400">อันตราย {area.danger}/4 · ทรัพยากร {Object.keys(area.loot).map(r=>resources[r as Resource]).join(" · ")}</p>
          {chosen !== location ? <div className="mt-4"><p className="mb-3 text-sm text-slate-400">{route ? `เดินทางใช้พลังงาน ${route.cost} / คุณมี ${mine.energy}` : "ไม่มีทางตรงจากตำแหน่งคุณ เลือกจุดที่เชื่อมต่อบนแผนที่"}</p><Button disabled={!mobile || !route || mine.energy < route.cost || Boolean(mine.encounter)} onClick={async()=>{if(await act("move",{location:chosen}))setSelected(null);}}>เดินทาง</Button></div> : <>
            <div className="mt-4 flex flex-wrap gap-2"><Button disabled={!day || mine.energy < 10 || Boolean(mine.encounter)} onClick={()=>void act("explore")}>ค้นหาของ −10 ⚡</Button><Button variant="secondary" disabled={!mobile || Boolean(mine.encounter)} onClick={()=>void act("rest")}>{location === "camp" ? "พักที่แคมป์" : "พักชั่วคราว"}</Button></div>
            <p className="mt-2 text-xs text-slate-500">พักได้ทุก 20 วินาที · แคมป์ฟื้นพลังงานและสุขภาพดีที่สุด</p>
            <div className="mt-4 flex flex-wrap gap-2">{Object.entries(s.ground[location]).filter(([,q])=>q>0).map(([r,q])=><Button key={r} variant="secondary" disabled={!mobile || mine.usedCapacity >= mine.capacity || Boolean(mine.encounter)} onClick={()=>void act("collect",{resource:r,quantity:1})}>เก็บ {resources[r as Resource]} · เหลือ {q}</Button>)}</div>
            {mine.localDrops.map(d=><div key={d.id} className="mt-4 rounded-lg border border-slate-700 p-3"><p className="text-xs text-amber-300">📦 ของที่วางไว้ · หมดอายุต้นวันที่ {d.expiresDay}</p><div className="mt-2 flex flex-wrap gap-2">{Object.entries(d.items).filter(([,q])=>q>0).map(([r,q])=><Button key={r} variant="secondary" disabled={!mobile || mine.usedCapacity>=mine.capacity || Boolean(mine.encounter)} onClick={()=>void act("pickup",{id:d.id,resource:r,quantity:1})}>{resources[r as Resource]} ×{q} · หยิบ 1</Button>)}</div></div>)}
            {s.nests.filter(n=>n.location===location&&n.hp>0).map(n=><div key={n.id} className="mt-4 rounded-xl border border-red-900 p-3"><p>👹 รังมอนสเตอร์ · HP {n.hp}/60</p><Button className="mt-2" variant="danger" disabled={!day||mine.energy<15||Boolean(mine.encounter)} onClick={()=>void act("nest",{id:n.id})}>ทำลายรัง −15 ⚡</Button><p className="mt-2 text-xs text-slate-400">ทำลายแล้วลดการเกิดมอนสเตอร์ในวันถัดไป</p></div>)}
            {mine.encounter && <div className="mt-4 rounded-xl border border-red-600 bg-red-950/60 p-4"><h3 className="font-semibold">👹 มอนสเตอร์ขวางทาง! HP {mine.encounter.hp}/{mine.encounter.maxHp}</h3><p className="my-2 text-sm">ความเสียหาย {mine.encounter.damage} · อยู่เป็นกลุ่มช่วยเพิ่มโอกาสรอด</p><div className="flex flex-wrap gap-2">{[["SNEAK","ลอบผ่าน −15 ⚡"],["DISTRACT","ล่อด้วยอาหาร 1"],["TORCH","ใช้คบไฟ 1"],["FIGHT","ต่อสู้ −15 ⚡"]].map(([choice,label])=><Button key={choice} variant="secondary" disabled={!mobile} onClick={()=>void act("encounter",{choice})}>{label}</Button>)}</div></div>}
            {s.phase === "NIGHT" && mine.role === "spy" && active && <div className="mt-4 rounded-xl border border-purple-900 bg-purple-950/40 p-4"><h3 className="font-semibold text-purple-300">🕵️ ปฏิบัติการส่วนตัว · ลงมือได้ 1 ครั้งต่อคืน</h3>{mine.nightUsed ? <p className="mt-2 text-sm">คุณลงมือคืนนี้แล้ว</p> : <><p className="mt-2 text-xs text-slate-400">เป้าหมายต้องอยู่ที่เดียวกัน การลงมือและตำแหน่งกลางคืนจะไม่ประกาศสาธารณะ</p><div className="mt-3 flex flex-wrap gap-2">{mine.nearbyPlayers.map(p=><Button key={p.userId} variant="danger" disabled={busy||Boolean(mine.encounter)} onClick={()=>setKillTarget(p.userId)}>ลอบฆ่า {p.username}</Button>)}</div>{location==="beach"&&<div className="mt-3 flex flex-wrap gap-2">{Object.keys(s.boat).map(c=><Button key={c} variant="danger" disabled={busy||!s.boat[c]||Boolean(mine.encounter)} onClick={()=>void act("sabotage",{component:c})}>ทำลาย {resources[c as Resource]}</Button>)}</div>}</>}</div>}
          </>}
        </Card>
        <Card><h2 className="font-semibold">🎯 ภารกิจส่วนกลาง</h2><div className="mt-4 space-y-4">{s.missions.map(m=><div key={m.id}>{progress(`${s.world[m.location].name} · ${resources[m.resource]}`,m.progress,m.quantity)}{m.location===location&&m.progress<m.quantity?<Button className="mt-2" variant="secondary" disabled={!day||!mine.inventory[m.resource]||Boolean(mine.encounter)} onClick={()=>void act("mission",{id:m.id,quantity:1})}>ส่งทรัพยากรให้ภารกิจ 1</Button>:<p className="mt-1 text-xs text-slate-500">{m.progress>=m.quantity?"✓ สำเร็จแล้ว":"เดินทางไปจุดภารกิจเพื่อส่งของ"}</p>}</div>)}</div></Card>
        <Card><h2 className="font-semibold">🚤 เรือที่ชายหาด</h2><p className="mt-2 text-sm text-slate-400">{location!=="beach"?"คุณต้องเดินทางไปชายหาดเพื่อสร้างเรือและขึ้นเรือ":"อยู่ที่ชายหาดแล้ว สามารถโต้ตอบกับเรือได้ตามช่วงเกม"}</p><div className="mt-4 grid grid-cols-2 gap-4">{Object.entries(s.boatCost).map(([r,total])=><div key={r}>{progress(resources[r as Resource],s.boat[r],total)}{location==="beach"&&s.phase==="DAY"&&<Button className="mt-2" variant="secondary" disabled={!day||!mine.inventory[r as Resource]||s.boat[r]>=total||Boolean(mine.encounter)} onClick={()=>void act("contribute",{resource:r,quantity:1})}>บริจาค 1</Button>}</div>)}</div>
          {s.phase==="ESCAPE"&&<div className="mt-5 space-y-3 border-t border-slate-700 pt-4"><p className="text-emerald-300">ภารกิจและเรือพร้อม! ที่นั่ง {s.occupiedSeats}/{s.seats}</p><p className="text-xs text-slate-400">ขึ้นเรือได้ที่ชายหาดเท่านั้น · เงื่อนไขผู้รอดชีวิต: {s.rules.survivorEscape==="all"?"ผู้รอดชีวิตที่ยังมีชีวิตทุกคน":s.rules.survivorEscape==="minimum"?`อย่างน้อย ${s.rules.minimumEscape} คน`:"อย่างน้อย 1 คน"}</p>{self?.escape?<p>คุณเลือก {self.escape==="BOARD"?"ขึ้นเรือ":"อยู่ต่อ"} แล้ว</p>:location==="beach"?<div className="flex gap-2"><Button disabled={!mobile||Boolean(mine.encounter)} onClick={()=>void act("escape",{choice:"BOARD"})}>ขึ้นเรือ</Button><Button variant="secondary" disabled={!mobile} onClick={()=>void act("escape",{choice:"STAY"})}>อยู่ต่อ</Button></div>:<Button variant="secondary" onClick={()=>setSelected("beach")}>ดูจุดหมายชายหาด</Button>}</div>}
        </Card>
        {s.phase==="DAY"&&<Card><h2 className="font-semibold">พบปะและแลกเปลี่ยน · {here.name}</h2><p className="mt-1 text-xs text-slate-400">ส่งของและแลกได้เฉพาะคนที่อยู่ด้วยกัน คำขอช่วยเปิดเผยสภาพของผู้ขอ</p><div className="mt-4 flex flex-wrap gap-2"><select aria-label="ผู้เล่นที่จะแลกหรือช่วย" className={cls} value={target} onChange={e=>setTarget(e.target.value)}><option value="">เลือกคนที่อยู่ด้วยกัน</option>{mine.nearbyPlayers.map(p=><option value={p.userId} key={p.userId}>{p.username}</option>)}</select>{selectResource(give,setGive,"ทรัพยากรที่ให้หรือขอ")}<input aria-label="จำนวนที่ให้หรือขอ" className={`${cls} w-20`} type="number" min={1} max={50} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/><Button variant="secondary" disabled={!day} onClick={()=>void act("request",{kind:"resource",resource:give,quantity})}>ขอของ</Button><Button variant="secondary" disabled={!day||!["food","water","medicine"].includes(give)} onClick={()=>void act("request",{kind:"help",resource:give,quantity:1})}>ขอความช่วยเหลือ</Button><Button variant="secondary" disabled={!day||!target||!["food","water","medicine"].includes(give)} onClick={()=>void act("help",{target,resource:give})}>ช่วย 1 ชิ้น</Button></div><div className="mt-4 flex flex-wrap items-center gap-2"><span className="text-sm">แลกกับ</span>{selectResource(want,setWant,"ทรัพยากรที่ต้องการ")}<input aria-label="จำนวนที่ต้องการ" className={`${cls} w-20`} type="number" min={1} max={50} value={wantQuantity} onChange={e=>setWantQuantity(Number(e.target.value))}/><Button disabled={!day||!target} onClick={()=>void act("offer",{target,give,want,giveQuantity:quantity,wantQuantity})}>เสนอแลก</Button></div>
          {mine.offers.filter(o=>o.status==="pending").map(o=><div key={o.id} className="mt-3 rounded-lg bg-slate-800 p-3 text-sm"><p>{name(o.from)} → {name(o.to)}: {resources[o.give.resource]} {o.give.quantity} แลก {resources[o.want.resource]} {o.want.quantity}</p>{o.to===selfUserId&&<div className="mt-2 flex gap-2"><Button disabled={!day} onClick={()=>void act("trade",{id:o.id,accept:true})}>ยอมรับ</Button><Button variant="secondary" disabled={!day} onClick={()=>void act("trade",{id:o.id,accept:false})}>ปฏิเสธ</Button></div>}</div>)}
          {s.requests.filter(r=>r.status==="open").map(r=><div key={r.id} className="mt-3 rounded-lg bg-slate-900 p-3 text-sm"><p>{name(r.from)} ขอ {resources[r.resource]} {r.quantity} · {s.world[r.location].name}</p>{r.kind==="help"&&<p className="text-amber-300">สุขภาพ {r.health} · ความอิ่ม {r.hunger} · น้ำ {r.thirst}</p>}{r.from!==selfUserId&&<Button className="mt-2" variant="secondary" disabled={!day||!mine.nearbyPlayers.some(p=>p.userId===r.from)} onClick={()=>void act("fulfill",{id:r.id})}>ส่งให้</Button>}</div>)}
        </Card>}
        <Card><h2 className="font-semibold">💬 แชตส่วนกลาง</h2><div role="log" className="my-4 max-h-72 space-y-2 overflow-y-auto text-sm">{s.chat.map(c=><p key={c.id} className="break-words"><span className="mr-2 text-emerald-300">{c.username}</span>{c.text}</p>)}</div><form className="flex flex-wrap gap-2" onSubmit={async e=>{e.preventDefault();if(await act("chat",{text}))setText("");}}><input aria-label="ข้อความแชต" className={`${cls} flex-1`} value={text} maxLength={300} disabled={!active} onChange={e=>setText(e.target.value)} placeholder="พูดคุย วางแผน หรือกล่าวหา…"/><Button type="submit" disabled={!active||busy||!text.trim()}>ส่ง</Button></form></Card>
      </div>
      <aside className="space-y-5">
        <Card><h2 className="font-semibold">สภาพของคุณ</h2><div className="mt-3 space-y-3">{[["❤️ สุขภาพ",mine.health],["⚡ พลังงาน",mine.energy],["🍖 ความอิ่ม",mine.hunger],["💧 น้ำในร่างกาย",mine.thirst]].map(([label,n])=><div key={label}>{progress(String(label),Number(n),100)}</div>)}</div><button className="mt-4 w-full rounded-xl border border-purple-900 p-3 text-left text-sm text-purple-200" onClick={()=>setShowRole(!showRole)}>{showRole?`บทบาท: ${mine.role.toUpperCase()} · เป้าหมายส่วนตัว: ${mine.objective}`:"🔒 กดดูบทบาทและเป้าหมายส่วนตัว"}</button>{showRole&&mine.allies.length>0&&<p className="mt-2 text-xs text-purple-300">Spy ร่วมทีม: {mine.allies.map(p=>p.username).join(", ")}</p>}</Card>
        <Card><h2 className="font-semibold">🎒 กระเป๋าระดับ {mine.bagLevel}</h2><div className="mt-3">{progress("ความจุ",mine.usedCapacity,mine.capacity)}</div>{mine.usedCapacity>=mine.capacity&&<p className="mt-2 text-xs text-amber-300">กระเป๋าเต็ม วางของเพื่อเพิ่มที่ว่าง</p>}<div className="mt-4 space-y-3">{Object.entries(mine.inventory).filter(([,q])=>q>0).map(([r,q])=><div key={r}><p className="text-sm">{resources[r as Resource]} ×{q}</p><div className="mt-1 flex gap-2">{["food","fruit","canned","energy_drink","water","medicine"].includes(r)&&<button className="rounded bg-slate-800 px-2 py-1 text-xs disabled:opacity-40" disabled={!mobile} onClick={()=>void act("use",{resource:r})}>ใช้ 1</button>}<button className="rounded bg-slate-800 px-2 py-1 text-xs disabled:opacity-40" disabled={!mobile} onClick={()=>void act("drop",{resource:r,quantity:1})}>วาง 1</button></div></div>)}</div>{mine.nextCapacity&&<div className="mt-4 border-t border-slate-700 pt-3"><p className="text-xs text-slate-400">อัปเกรดเป็น {mine.nextCapacity} ช่อง · เชือก 2 โลหะ 2 ชิ้นส่วน 1 · ที่แคมป์/โรงงาน</p>{["camp","workshop"].includes(location)&&<Button className="mt-2" variant="secondary" disabled={!day||Boolean(mine.encounter)} onClick={()=>void act("upgrade")}>อัปเกรดกระเป๋า</Button>}</div>}</Card>
        <Card><h2 className="font-semibold">ผู้เล่น</h2><ul className="mt-3 space-y-2 text-sm">{s.players.map(p=><li key={p.userId}><span className={p.alive?"text-emerald-400":"text-slate-500"}>{p.alive?"●":"☠"}</span> {p.username}{p.userId===selfUserId?" (คุณ)":""}<span className="block text-xs text-slate-500">{p.alive?s.world[p.location].name:"ผู้ชม"}{p.revealedRole?` · ${p.revealedRole}`:""}{!p.connected?" · ออฟไลน์":""}</span></li>)}</ul></Card>
        <Card><h2 className="font-semibold">👁️ หลักฐานส่วนตัว</h2><ul className="mt-3 max-h-64 space-y-3 overflow-y-auto text-xs text-amber-200">{mine.evidence.map((e,i)=><li key={i}>{e}</li>)}</ul></Card>
        <Card><h2 className="font-semibold">📜 บันทึกเกาะ</h2><ol className="mt-3 max-h-96 space-y-3 overflow-y-auto text-xs text-slate-400">{[...s.logs].reverse().map(l=><li key={l.id}><span className="text-emerald-400">วันที่ {l.day}</span> · {l.text}</li>)}</ol></Card>
      </aside>
    </div>
    {showVote&&s.phase==="VOTE"&&active&&<Popup title="🗳️ ใครคือ Spy?" onClose={()=>setShowVote(false)}><Timer endsAt={s.phaseEndsAt}/>{mine.votedFor?<p className="mt-4">คุณโหวต {name(mine.votedFor)} แล้ว</p>:<><p className="my-4 text-sm text-slate-400">เลือกแล้วกดยืนยัน เปลี่ยนโหวตไม่ได้ · การโหวตไม่ทำให้เกมจบ</p><div className="grid grid-cols-2 gap-2">{s.players.filter(p=>p.alive&&p.connected&&p.userId!==selfUserId).map(p=><Button key={p.userId} variant={vote===p.userId?"primary":"secondary"} onClick={()=>setVote(p.userId)}>{p.username}</Button>)}</div><Button className="mt-4" disabled={!vote||busy} onClick={async()=>{if(await act("vote",{target:vote}))setShowVote(false);}}>ยืนยันโหวต</Button></>}{error&&<p className="mt-3 text-red-300">{error}</p>}</Popup>}
    {killTarget&&<Popup title="ยืนยันการลอบฆ่า" onClose={()=>setKillTarget(null)}><p>ลงมือกับ {name(killTarget)} ใช้สิทธิ์ปฏิบัติการคืนนี้</p><Button variant="danger" className="mt-4" disabled={busy} onClick={async()=>{if(await act("kill",{target:killTarget}))setKillTarget(null);}}>ยืนยัน</Button>{error&&<p className="mt-3 text-red-300">{error}</p>}</Popup>}
    {alertText&&<Popup title="เสียงเตือนจากเกาะ" onClose={()=>setAlertText(null)}><p className="text-amber-200">{alertText}</p><Button className="mt-4" onClick={()=>setAlertText(null)}>รับทราบ</Button></Popup>}
  </main>;
}
