import { useEffect, useRef, useState } from "react";
import type { CSSProperties, ReactNode } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "../../components/common/Button";
import { Card } from "../../components/common/Card";
import { Timer } from "../../components/common/Timer";
import type { GameComponentProps } from "../registry";
import { locations, resources, type IslandPublic, type IslandPrivate, type Resource, type Location } from "./types";
import { TruthReveal } from "./TruthReveal";
const phases = { DAY_START: "รุ่งเช้า", ACTION: "สำรวจและเอาชีวิตรอด", SECRET: "คืนแห่งความลับ", EVENT: "เหตุการณ์บนเกาะ", SURVIVAL: "อาหาร น้ำ และผู้รอดชีวิต", ESCAPE: "ถึงเวลาหนี", FINISHED: "จบเกมแล้ว" };
const inputClass = "min-w-0 rounded-lg border border-slate-700 bg-slate-900 p-2 text-sm text-white";
function Popup({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { ref.current?.showModal(); return () => ref.current?.close(); }, []);
  return <dialog ref={ref} onCancel={e => { e.preventDefault(); onClose(); }} className="w-[min(94vw,32rem)] rounded-2xl border border-slate-700 bg-slate-950 p-6 text-white backdrop:bg-black/75"><div className="mb-5 flex items-start justify-between gap-4"><h2 className="text-xl font-semibold">{title}</h2><button autoFocus aria-label="ปิดหน้าต่าง" className="rounded-lg px-3 py-1 text-xl hover:bg-slate-800" onClick={onClose}>×</button></div>{children}</dialog>;
}
export function IslandBetrayalGame({ room, publicState, privateState, selfUserId, onAction }: GameComponentProps) {
  const s = publicState as IslandPublic | null, mine = privateState as IslandPrivate | null;
  const navigate = useNavigate();
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [text, setText] = useState(""); const [target, setTarget] = useState("");
  const [give, setGive] = useState<Resource>("food"), [want, setWant] = useState<Resource>("water");
  const [giveQuantity, setGiveQuantity] = useState(1), [wantQuantity, setWantQuantity] = useState(1);
  const [secretKind, setSecretKind] = useState("SKIP"), [secretTarget, setSecretTarget] = useState("boat");
  const [component, setComponent] = useState("wood"); const [modal, setModal] = useState<"secret" | "escape" | null>(null);
  const [showObjective, setShowObjective] = useState(false);
  const me = s?.players.find(p => p.userId === selfUserId);
  const active = Boolean(me?.alive && me?.connected);
  const canAct = active && s?.phase === "ACTION" && !busy;
  const others = s?.players.filter(p => p.userId !== selfUserId && p.alive && p.connected) ?? [];
  useEffect(() => { setModal(s?.phase === "SECRET" ? "secret" : s?.phase === "ESCAPE" ? "escape" : null); setError(""); }, [s?.phase, s?.day]);
  async function act(type: string, payload: unknown = {}) {
    if (busy) return false;
    setBusy(true); setError("");
    try { const r = await onAction(`island:${type}`, payload); if (!r.ok) setError(r.error ?? "ทำรายการไม่สำเร็จ"); return r.ok; }
    catch { setError("การเชื่อมต่อขัดข้อง กรุณาลองใหม่"); return false; }
    finally { setBusy(false); }
  }
  const name = (id: string) => s?.players.find(p => p.userId === id)?.username ?? id;
  const resourceSelect = (value: Resource, change: (r: Resource) => void, label: string, healing = false) => <select aria-label={label} className={inputClass} value={value} onChange={e => change(e.target.value as Resource)}>{Object.entries(resources).filter(([r]) => !healing || ["food", "water", "medicine"].includes(r)).map(([r, label]) => <option value={r} key={r}>{label}</option>)}</select>;
  if (!s || !mine || !me) return <Card className="mx-auto mt-8 max-w-xl">กำลังโหลดเกาะและข้อมูลส่วนตัว…</Card>;
  if (s.phase === "FINISHED" && s.result) return <main className="mx-auto max-w-5xl space-y-5 p-4 sm:p-8"><Card><TruthReveal result={s.result} /><Button className="mt-6" variant="secondary" onClick={() => navigate(`/lobby/${room.roomCode}`)}>กลับไปที่ล็อบบี้</Button></Card></main>;
  const secretForm = <div className="space-y-4">
    <p className="text-sm text-slate-400">เลือกได้ครั้งเดียว ระบบจะเปิดเผยหลังจบเกม · ไม่เลือกภายในเวลาถือว่าข้าม</p>
    <Timer endsAt={s.phaseEndsAt} />
    {mine.secret ? <p className="rounded-xl bg-emerald-950 p-4 text-emerald-300">ล็อกแอ็กชันแล้ว รอผู้เล่นที่เหลือหรือหมดเวลา</p> : <>
      <select aria-label="แอ็กชันลับ" className={`${inputClass} w-full`} value={secretKind} onChange={e => { setSecretKind(e.target.value); setSecretTarget(e.target.value === "INVESTIGATE" ? "boat" : others[0]?.userId ?? ""); }}>{[["SKIP", "ข้าม"], ["HELP", "ช่วยเหลือ"], ["INVESTIGATE", "สืบสวน"], ["STEAL", "ขโมย"], ["SABOTAGE", "ก่อวินาศกรรม"]].map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select>
      {["HELP", "STEAL", "INVESTIGATE"].includes(secretKind) && <select aria-label="เป้าหมายแอ็กชันลับ" className={`${inputClass} w-full`} value={secretTarget} onChange={e => setSecretTarget(e.target.value)}><option value="" disabled>เลือกเป้าหมาย</option>{others.map(p => <option key={p.userId} value={p.userId}>{p.username}</option>)}{secretKind === "INVESTIGATE" && <><option value="boat">เรือ</option><option value="event">เหตุการณ์</option>{Object.entries(locations).map(([id, l]) => <option key={id} value={id}>{l.label}</option>)}</>}</select>}
      {secretKind === "HELP" && resourceSelect(give, setGive, "ของสำหรับช่วยเหลือ", true)}
      {secretKind === "SABOTAGE" && <select aria-label="ส่วนเรือ" className={inputClass} value={component} onChange={e => setComponent(e.target.value)}>{Object.keys(s.boatCost).map(r => <option value={r} key={r}>{resources[r as Resource]}</option>)}</select>}
      <Button disabled={!active || busy} onClick={async () => { if (await act("secret", { kind: secretKind, target: secretTarget, resource: give, component })) setModal(null); }}>ยืนยันและล็อกแอ็กชัน</Button>
    </>}
  </div>;
  const escapeForm = <div className="space-y-4"><p className="text-slate-300">ที่นั่ง {s.occupiedSeats}/{s.seats} · ขึ้นก่อนได้ก่อน เลือกแล้วเปลี่ยนไม่ได้ ผู้ที่ไม่เลือกจะอยู่บนเกาะ</p><Timer endsAt={s.phaseEndsAt} />{me.escape ? <p className="text-emerald-300">คุณเลือก{me.escape === "BOARD" ? "ขึ้นเรือ" : "อยู่บนเกาะ"}แล้ว</p> : <div className="flex gap-3"><Button disabled={!active || busy || s.occupiedSeats >= s.seats} onClick={() => void act("escape", { choice: "BOARD" })}>🚤 ขึ้นเรือ</Button><Button variant="secondary" disabled={!active || busy} onClick={() => void act("escape", { choice: "STAY" })}>อยู่บนเกาะ</Button></div>}{me.escape === "BOARD" && <div className="space-y-3 border-t border-slate-800 pt-4"><p className="text-sm text-slate-400">แอ็กชันพิเศษ: ใช้เชือก 1 ช่วยผู้ที่ยังไม่เลือกขึ้นที่นั่งว่าง</p><select aria-label="ผู้เล่นที่จะช่วยขึ้นเรือ" value={target} onChange={e => setTarget(e.target.value)} className={inputClass}><option value="">เลือกคนที่จะช่วย</option>{others.filter(p => !p.escape).map(p => <option key={p.userId} value={p.userId}>{p.username}</option>)}</select><Button disabled={!active || busy || !target} onClick={() => void act("escape", { choice: "RESCUE", target })}>ช่วยขึ้นเรือ</Button></div>}</div>;
  return <main className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6">
    <Card className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-emerald-400">{room.roomName} · วันที่ {s.day}/10</p><h1 className="mt-1 text-2xl font-semibold">Island Betrayal</h1><p className="mt-1 text-sm text-slate-400">{phases[s.phase]} · {s.weather}</p></div><Timer endsAt={s.phaseEndsAt} /></Card>
    {!active && <p className="rounded-xl border border-amber-800 bg-amber-950/40 p-4 text-amber-300">{!me.alive ? "คุณเสียชีวิตแล้ว — รับชมแผนที่ เหตุการณ์ และแชตได้จนจบเกม" : "คุณอยู่ในสถานะออกจากเกม กรุณากลับเข้าห้องเพื่อเล่นต่อ"}</p>}
    {error && <p role="alert" className="rounded-xl border border-red-800 bg-red-950 p-3 text-red-200">{error}</p>}
    {s.phase === "SECRET" && <Card><h2 className="mb-3 font-semibold">🌙 แอ็กชันลับ</h2><Button disabled={!active} onClick={() => setModal("secret")}>{mine.secret ? "ดูสถานะแอ็กชันที่ล็อกแล้ว" : "เลือกแอ็กชันลับ"}</Button></Card>}
    {s.phase === "ESCAPE" && <Card><h2 className="mb-3 font-semibold">🚤 เรือพร้อมแล้ว</h2><Button disabled={!active} onClick={() => setModal("escape")}>เลือกการหนี · {s.occupiedSeats}/{s.seats} ที่นั่ง</Button></Card>}
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_20rem]">
      <div className="space-y-5">
        <Card><div className="mb-4 flex flex-wrap justify-between gap-2"><h2 className="font-semibold">แผนที่เกาะ</h2><p className="text-xs text-slate-400">เดินทาง −1 พลังงาน · สำรวจ −2</p></div>
          <div className="relative grid grid-cols-2 gap-2 overflow-hidden rounded-2xl border border-cyan-900 bg-cyan-950/50 p-3 sm:block sm:h-[420px]">
            <svg aria-hidden="true" viewBox="0 0 700 420" preserveAspectRatio="none" className="pointer-events-none absolute inset-0 h-full w-full opacity-60"><path d="M95 175 Q80 70 220 60 Q340 0 490 35 Q680 80 610 220 Q680 355 470 385 Q290 430 145 330 Q15 280 95 175Z" fill="#145345" stroke="#5f9c77" strokeWidth="12"/><path d="M100 390 Q310 330 690 390 M15 35 Q330 -10 700 40" fill="none" stroke="#155e75" strokeWidth="6"/></svg>
            {Object.entries(locations).map(([id, l]) => <button key={id} disabled={!canAct || me.location === id} onClick={() => void act("move", { location: id })} style={{ "--map-x": `${l.x}%`, "--map-y": `${l.y}%` } as CSSProperties} className={`relative z-10 rounded-xl border p-2 text-left transition sm:absolute sm:left-[var(--map-x)] sm:top-[var(--map-y)] sm:w-[28%] sm:-translate-x-1/2 sm:-translate-y-1/2 ${me.location === id ? "border-emerald-400 bg-emerald-950 ring-2 ring-emerald-700" : "border-slate-600 bg-slate-950/90 hover:border-cyan-400"}`}><span className="block text-sm font-semibold">{l.label}{me.location === id ? " · คุณ" : ""}</span><span className="mt-1 block text-[10px] leading-4 text-slate-400">{l.loot}</span><span className="mt-1 block truncate text-xs text-emerald-300">{s.players.filter(p => p.alive && p.location === id).map(p => p.username).join(", ") || "ไม่มีผู้เล่น"}</span></button>)}
          </div>
          <div className="mt-4 flex flex-wrap items-center gap-3"><span className="text-sm">คุณอยู่ที่ {locations[me.location].label}</span><Button disabled={!canAct || mine.energy < 2} onClick={() => void act("explore")}>สำรวจ −2 ⚡</Button></div>
          <p className="mt-3 text-xs text-slate-400">ของที่พบเป็นของส่วนกลางในจุดนี้ ใครเก็บก่อนจะได้ก่อน · สำรวจมีโอกาสบาดเจ็บ</p><div className="mt-3 flex flex-wrap gap-2">{Object.entries(s.ground[me.location]).filter(([, q]) => q > 0).map(([r, q]) => <Button variant="secondary" key={r} disabled={!canAct} onClick={() => void act("collect", { resource: r, quantity: 1 })}>เก็บ {resources[r as Resource]} 1/{q}</Button>)}</div>
        </Card>
        <Card><h2 className="font-semibold">🚤 เรือหนีออกจากเกาะ</h2><p className="mt-1 text-xs text-slate-400">บริจาคได้ที่ชายหาด · เรือครบแล้วเข้าสู่ช่วงหนี 45 วินาที</p><div className="mt-4 grid grid-cols-2 gap-3">{Object.entries(s.boatCost).map(([r, total]) => <div key={r} className="rounded-xl bg-slate-900 p-3"><div className="flex justify-between text-sm"><span>{resources[r as Resource]}</span><span>{s.boat[r]}/{total}</span></div><progress aria-label={`ความคืบหน้า ${resources[r as Resource]}`} max={total} value={s.boat[r]} className="my-2 h-2 w-full accent-emerald-500"/><Button variant="secondary" disabled={!canAct || me.location !== "beach" || !mine.inventory[r as Resource] || s.boat[r] >= total} onClick={() => void act("contribute", { resource: r, quantity: 1 })}>บริจาค 1</Button></div>)}</div></Card>
        <Card><h2 className="font-semibold">ขอของ · ช่วยเหลือ · แลกเปลี่ยน</h2><p className="mt-1 text-xs text-slate-400">แลกและส่งของเมื่ออยู่ที่เดียวกัน · การคุยในแชตไม่ทำให้ของย้าย</p>
          <div className="mt-4 grid gap-3 sm:grid-cols-2"><select aria-label="ผู้เล่นเป้าหมาย" value={target} onChange={e => setTarget(e.target.value)} className={inputClass}><option value="">เลือกผู้เล่น</option>{others.map(p => <option key={p.userId} value={p.userId}>{p.username} · {locations[p.location].label}</option>)}</select>{resourceSelect(give, setGive, "ทรัพยากรที่ให้หรือขอ")}<label className="text-xs text-slate-400">จำนวนที่ให้ / ขอ<input className={`${inputClass} ml-2 w-20`} type="number" min={1} max={50} value={giveQuantity} onChange={e => setGiveQuantity(Number(e.target.value))}/></label><Button variant="secondary" disabled={!canAct || !target} onClick={() => void act("help", { target, resource: give })}>ช่วยด้วยอาหาร น้ำ หรือยา 1</Button></div>
          <div className="mt-3 flex flex-wrap gap-2"><Button variant="secondary" disabled={!canAct} onClick={() => void act("request", { kind: "resource", resource: give, quantity: giveQuantity })}>ขอทรัพยากร</Button><Button variant="secondary" disabled={!canAct} onClick={() => void act("request", { kind: "help", resource: give, quantity: 1 })}>ขอความช่วยเหลือ (เปิดเผยสภาพตัวเอง)</Button></div>
          <div className="mt-5 flex flex-wrap items-center gap-2 border-t border-slate-800 pt-4"><span className="text-sm">ต้องการแลกกับ</span>{resourceSelect(want, setWant, "ทรัพยากรที่ต้องการแลก")}<input aria-label="จำนวนที่ต้องการแลก" type="number" min={1} max={50} className={`${inputClass} w-20`} value={wantQuantity} onChange={e => setWantQuantity(Number(e.target.value))}/><Button disabled={!canAct || !target} onClick={() => void act("offer", { target, give, want, giveQuantity, wantQuantity })}>ส่งข้อเสนอส่วนตัว</Button></div>
          <div className="mt-4 space-y-3">{mine.offers.filter(o => o.status === "pending").map(o => <div key={o.id} className="rounded-lg border border-slate-700 p-3 text-sm"><p>{name(o.from)} → {name(o.to)}: {resources[o.give.resource]} {o.give.quantity} แลก {resources[o.want.resource]} {o.want.quantity}</p>{o.to === selfUserId ? <div className="mt-2 flex gap-2"><Button disabled={!canAct} onClick={() => void act("trade", { id: o.id, accept: true })}>ยอมรับ</Button><Button variant="secondary" disabled={!canAct} onClick={() => void act("trade", { id: o.id, accept: false })}>ปฏิเสธ</Button></div> : <p className="mt-2 text-slate-500">รอผู้รับตอบ</p>}</div>)}</div>
          <div className="mt-4 space-y-3">{s.requests.filter(r => r.status === "open").map(r => <div key={r.id} className="rounded-lg bg-slate-900 p-3 text-sm"><p>{name(r.from)} ขอ{resources[r.resource]} {r.quantity} · {locations[r.location].label}</p>{r.kind === "help" && <p className="mt-1 text-amber-300">สุขภาพ {r.health} · ความอิ่ม {r.hunger} · น้ำ {r.thirst}</p>}{r.from !== selfUserId && <Button className="mt-2" variant="secondary" disabled={!canAct} onClick={() => void act("fulfill", { id: r.id })}>ส่งให้ / ช่วย</Button>}</div>)}</div>
        </Card>
        <Card><h2 className="font-semibold">💬 คุยบนเกาะ</h2><div className="my-4 max-h-64 space-y-2 overflow-y-auto text-sm" role="log">{s.chat.length === 0 && <p className="text-slate-500">นัดพบ ขอความร่วมมือ หรือเตือนเพื่อนได้ที่นี่</p>}{s.chat.map(c => <p key={c.id} className="break-words"><span className="mr-2 font-semibold text-emerald-300">{c.username}</span>{c.text}</p>)}</div><form className="flex flex-wrap gap-2" onSubmit={async e => { e.preventDefault(); if (await act("chat", { text })) setText(""); }}><input aria-label="ข้อความแชต" maxLength={300} className={`${inputClass} flex-1`} value={text} disabled={!active} onChange={e => setText(e.target.value)} placeholder="พิมพ์ข้อความ…"/><Button type="submit" disabled={!active || busy || !text.trim()}>ส่ง</Button><Button type="button" variant="secondary" disabled={!canAct || !text.trim()} onClick={async () => { if (await act("warning", { text })) setText(""); }}>ส่งคำเตือน</Button></form></Card>
      </div>
      <aside className="space-y-5">
        <Card><h2 className="font-semibold">สภาพของคุณ</h2><div className="mt-4 space-y-3">{[["❤️ สุขภาพ", mine.health, 100], ["⚡ พลังงาน", mine.energy, 10], ["🍖 ความอิ่ม", mine.hunger, 100], ["💧 น้ำในร่างกาย", mine.thirst, 100]].map(([label, value, max]) => <div key={label}><div className="flex justify-between text-sm"><span>{label}</span><span>{value}/{max}</span></div><progress aria-label={String(label)} value={Number(value)} max={Number(max)} className="h-2 w-full accent-emerald-500"/></div>)}</div><button className="mt-5 w-full rounded-xl border border-amber-900 bg-amber-950/30 p-3 text-left text-sm text-amber-200" onClick={() => setShowObjective(!showObjective)}>{showObjective ? `🎯 ${mine.objective}` : "🎯 กดเพื่อดูเป้าหมายลับของคุณ"}</button></Card>
        <Card><h2 className="font-semibold">กระเป๋าส่วนตัว</h2><p className="mt-1 text-xs text-slate-500">มีเพียงคุณที่เห็นจำนวนของในกระเป๋านี้</p><div className="mt-4 space-y-2">{Object.entries(resources).map(([r, label]) => <div key={r} className="flex items-center justify-between gap-2 text-sm"><span>{label}</span><span className="ml-auto font-mono">{mine.inventory[r as Resource]}</span>{["food", "water", "medicine"].includes(r) && <button className="rounded bg-slate-800 px-2 py-1 disabled:opacity-40" disabled={!canAct || !mine.inventory[r as Resource]} onClick={() => void act("use", { resource: r })}>ใช้ 1</button>}</div>)}</div></Card>
        <Card><h2 className="font-semibold">ผู้รอดชีวิต</h2><ul className="mt-3 space-y-3 text-sm">{s.players.map(p => <li key={p.userId}><span className={p.alive ? "text-emerald-300" : "text-slate-500"}>{p.alive ? p.connected ? "●" : "○" : "☠"}</span> {p.username}{p.userId === selfUserId ? " (คุณ)" : ""}<span className="block text-xs text-slate-500">{p.alive ? locations[p.location].label : "ผู้ชม"}{!p.connected ? " · ออกจากเกม" : ""}</span></li>)}</ul></Card>
        <Card><h2 className="font-semibold">หลักฐานส่วนตัว</h2><ul className="mt-3 max-h-60 space-y-3 overflow-y-auto text-xs text-amber-200">{mine.evidence.length ? mine.evidence.map((e, i) => <li key={i}>{e}</li>) : <li className="text-slate-500">ยังไม่มีหลักฐาน</li>}</ul></Card>
        <Card><h2 className="font-semibold">บันทึกเกาะ</h2><ol className="mt-3 max-h-80 space-y-3 overflow-y-auto text-xs text-slate-400">{[...s.logs].reverse().map(l => <li key={l.id}><span className="text-emerald-400">วันที่ {l.day}</span> · {l.text}</li>)}</ol></Card>
      </aside>
    </div>
    {modal && active && <Popup title={modal === "secret" ? "🌙 เลือกแอ็กชันลับ" : "🚤 หนีออกจากเกาะ"} onClose={() => setModal(null)}>{modal === "secret" ? secretForm : escapeForm}{error && <p role="alert" className="mt-3 text-sm text-red-300">{error}</p>}</Popup>}
  </main>;
}
