import { useRef, useState } from "react";
import type { IslandPublic } from "./types";
import { Button } from "../../components/common/Button";
export function IslandMap({ state: s, location, onSelect }: { state: IslandPublic; location: string; onSelect: (id: string) => void }) {
  const [camera, setCamera] = useState({ x: -100, y: -90, zoom: .8 });
  const drag = useRef<{ x: number; y: number; cx: number; cy: number; moved: boolean } | null>(null);
  const svg = useRef<SVGSVGElement>(null);
  const focus = () => { const p = s.world[location]; setCamera(c => ({ ...c, x: 500 - p.x * c.zoom, y: 300 - p.y * c.zoom })); };
  const zoom = (amount: number) => setCamera(c => { const z = Math.min(1.6, Math.max(.4, c.zoom + amount)); return { zoom: z, x: 500 - (500 - c.x) * z / c.zoom, y: 300 - (300 - c.y) * z / c.zoom }; });
  return <div className="overflow-hidden rounded-2xl border border-cyan-900 bg-slate-950">
    <div className="flex flex-wrap items-center justify-between gap-2 p-3"><p className="text-xs text-cyan-300">เกาะเดียว · ลากเพื่อเลื่อน · เลือกพื้นที่เพื่อดูเส้นทาง</p><div className="flex gap-1"><Button variant="secondary" aria-label="ซูมออก" onClick={() => zoom(-.15)}>−</Button><Button variant="secondary" aria-label="ซูมเข้า" onClick={() => zoom(.15)}>+</Button><Button variant="secondary" onClick={focus}>ตำแหน่งฉัน</Button></div></div>
    <div className="relative"><svg ref={svg} viewBox="0 0 1000 600" className="h-[420px] w-full touch-none bg-[#062637] sm:h-[540px]" aria-label="แผนที่เกาะแบบลากและซูม" onPointerDown={e => { const box = e.currentTarget.getBoundingClientRect(); drag.current = { x: e.clientX * 1000 / box.width, y: e.clientY * 1000 / box.width, cx: camera.x, cy: camera.y, moved: false }; }} onPointerMove={e => { if (!drag.current || !e.buttons && e.pointerType === "mouse") return; const box = e.currentTarget.getBoundingClientRect(), dx = e.clientX * 1000 / box.width - drag.current.x, dy = e.clientY * 1000 / box.width - drag.current.y; if (Math.abs(dx) + Math.abs(dy) > 8) { drag.current.moved = true; const origin = drag.current; setCamera(c => ({ ...c, x: Math.max(-1700, Math.min(900, origin.cx + dx)), y: Math.max(-1300, Math.min(500, origin.cy + dy)) })); } }} onPointerUp={() => { setTimeout(() => { drag.current = null; }, 0); }} onPointerLeave={() => { drag.current = null; }}>
      <defs><radialGradient id="island-land"><stop stopColor="#32664e"/><stop offset="1" stopColor="#153d37"/></radialGradient></defs>
      <g transform={`translate(${camera.x},${camera.y}) scale(${camera.zoom})`}>
        <path d="M120 660 Q40 360 350 210 Q460 50 820 65 Q1190 -20 1390 245 Q1570 420 1480 790 Q1570 1100 1150 1130 Q750 1260 440 1040 Q80 1060 120 660Z" fill="url(#island-land)" stroke="#9a9564" strokeWidth="24"/>
        {s.routes.map(r => <line key={r.from+r.to} x1={s.world[r.from].x} y1={s.world[r.from].y} x2={s.world[r.to].x} y2={s.world[r.to].y} stroke="#a4b59b" strokeWidth="5" strokeDasharray="10 8" opacity=".55"/>)}
        {Object.entries(s.world).map(([id, p]) => { const people = s.players.filter(t => t.alive && t.location === id); const missions = s.missions.filter(m => m.location === id && m.progress < m.quantity).length; const monsters = s.monsters.filter(m => m.hp > 0 && m.location === id).length; return <g key={id} role="button" tabIndex={0} aria-label={p.name} className="cursor-pointer" onClick={() => { if (!drag.current?.moved) onSelect(id); }} onKeyDown={e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); onSelect(id); } }} transform={`translate(${p.x},${p.y})`}><rect x="-96" y="-40" width="192" height="92" rx="18" fill={location === id ? "#064e3b" : "#0f172a"} stroke={location === id ? "#6ee7b7" : "#6b887b"} strokeWidth={location === id ? 4 : 2}/><text textAnchor="middle" y="-10" fill="#f8fafc" fontSize="19">{p.name}</text><text textAnchor="middle" y="14" fill="#94a3b8" fontSize="13">อันตราย {p.danger}/4 {missions ? `· 🎯 ${missions}` : ""} {monsters ? `· 👹 ${monsters}` : ""}</text><text textAnchor="middle" y="37" fill="#6ee7b7" fontSize="13">{location === id ? "📍 คุณ · " : ""}{people.length ? `${people.length} ผู้เล่น` : "ไม่มีผู้เล่น"}</text></g>; })}
      </g>
    </svg><svg viewBox="0 0 1600 1200" className="absolute bottom-3 right-3 h-24 w-32 cursor-crosshair rounded-lg border border-cyan-700 bg-slate-950/90" role="img" aria-label="มินิแมป กดเพื่อเลื่อนแผนที่" onClick={e => { const box=e.currentTarget.getBoundingClientRect(); const x=(e.clientX-box.left)/box.width*1600,y=(e.clientY-box.top)/box.height*1200; setCamera(c=>({...c,x:500-x*c.zoom,y:300-y*c.zoom})); }}><ellipse cx="800" cy="600" rx="690" ry="530" fill="#214b3c"/>{Object.entries(s.world).map(([id,p])=><circle key={id} cx={p.x} cy={p.y} r={id===location?34:20} fill={id===location?'#6ee7b7':'#a1a1aa'}/>)}<rect x={-camera.x/camera.zoom} y={-camera.y/camera.zoom} width={1000/camera.zoom} height={600/camera.zoom} fill="none" stroke="#fbbf24" strokeWidth="12"/></svg></div>
  </div>;
}
