const fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);
const {test}=require('node:test'),a=require('node:assert/strict'),{ItoGame}=require('../src/games/ito/ItoGame.ts');
function make(n=3,mode='TABLE'){const g=new ItoGame('r',{ito:{mode}});for(let i=0;i<n;i++)g.addPlayer({userId:`p${i}`,username:`Player${i}`});g.start();return g;}
const act=(g,id,t,p={})=>g.handleAction(id,`ito:${t}`,p);
const cards=g=>g.getPlayers().flatMap(p=>g.getPrivateState(p.userId).cards.map(c=>({...c,userId:p.userId}))).sort((a,b)=>a.value-b.value);
function play(g,c){act(g,c.userId,'propose',{cardId:c.id});const p=g.getPublicState().proposal;for(const u of g.getPlayers())if(u.userId!==c.userId)act(g,u.userId,'vote',{proposalId:p.id,accept:true});}
const clue=g=>cards(g).forEach(c=>act(g,c.userId,'clue',{cardId:c.id,text:'กาแฟอุ่น'}));
test('privacy, unique deck for 2–8 players and independent private copies',()=>{for(let n=2;n<=8;n++){const g=make(n);try{a.equal(new Set(cards(g).map(c=>c.value)).size,n);a.ok(cards(g).every(c=>c.value>=1&&c.value<=100));a.equal(g.getPrivateState('outsider'),null);for(const p of g.getPublicState().players)for(const c of p.cards)a.equal('value' in c,false);const p=g.getPrivateState('p0');p.cards[0].value=999;a.notEqual(g.getPrivateState('p0').cards[0].value,999);a.throws(()=>act(g,'outsider','ready'));a.throws(()=>act(g,'p1','propose',{cardId:p.cards[0].id}));}finally{g.end();}}});
test('both modes win all three stages; end is idempotent',()=>{for(const mode of ['TABLE','ONLINE']){const g=make(4,mode);let ended=0;g.on('ended',()=>ended++);for(let round=1;round<=3;round++){a.equal(cards(g).length,round*4);if(mode==='ONLINE')clue(g);for(const c of cards(g))play(g,c);if(round<3){a.equal(g.getPublicState().phase,'ROUND_END');for(const p of g.getPlayers())act(g,p.userId,'ready');}}a.equal(ended,1);a.equal(g.end().winnerUserIds.length,4);g.end();a.equal(ended,1);a.equal(g.timer,null);}});
test('online clue validation, all clues required, rejection and stale votes',()=>{const g=make(3,'ONLINE');try{const c=cards(g)[0];a.throws(()=>act(g,c.userId,'propose',{cardId:c.id}));for(const text of ['',23,'99','๙','x'.repeat(161)])a.throws(()=>act(g,c.userId,'clue',{cardId:c.id,text}));clue(g);act(g,c.userId,'propose',{cardId:c.id});const p=g.getPublicState().proposal;const other=g.getPlayers().find(x=>x.userId!==c.userId).userId;a.throws(()=>act(g,c.userId,'vote',{proposalId:p.id,accept:true}));a.throws(()=>act(g,other,'vote',{proposalId:'old',accept:true}));a.throws(()=>act(g,c.userId,'clue',{cardId:c.id,text:'แก้ไข'}));act(g,other,'vote',{proposalId:p.id,accept:false});a.equal(g.getPublicState().proposal,null);a.equal(g.getPublicState().revealed.length,0);a.throws(()=>act(g,other,'vote',{proposalId:p.id,accept:true}));}finally{g.end();}});
test('three mistakes cost three hearts, remove lower cards and lose',()=>{const g=make();for(let round=1;round<=3;round++){play(g,cards(g).at(-1));a.equal(g.getPublicState().lives,3-round);a.equal(cards(g).length,0);if(round<3)for(const p of g.getPlayers())act(g,p.userId,'ready');}a.deepEqual(g.end().winnerUserIds,[]);});
test('disconnect keeps cards, cancels ballot and reconnect resumes',()=>{const g=make();try{const before=g.getPrivateState('p1');const c=cards(g)[0];act(g,c.userId,'propose',{cardId:c.id});g.removePlayer('p1');a.equal(g.getPublicState().proposal,null);a.throws(()=>act(g,'p0','propose',{cardId:g.getPrivateState('p0').cards[0].id}));g.reconnectPlayer('p1');a.deepEqual(g.getPrivateState('p1'),before);play(g,c);a.equal(g.getPublicState().revealed.length,1);}finally{g.end();}});
test('abandoned game times out and timer clears',t=>{t.mock.timers.enable({apis:['Date','setTimeout']});const g=make();t.mock.timers.tick(600001);a.equal(g.getPublicState().phase,'FINISHED');a.equal(g.timer,null);a.deepEqual(g.end().winnerUserIds,[]);a.throws(()=>act(g,'p0','ready'));t.mock.timers.reset();});
test('room schema preserves mode and rejects invalid settings',()=>{const {createRoomSchema}=require('../src/utils/validators.ts');for(const mode of ['TABLE','ONLINE'])a.equal(createRoomSchema.parse({gameSlug:'ito',roomName:'Test',maxPlayers:2,settings:{ito:{mode}}}).settings.ito.mode,mode);for(const ito of [{mode:'bad'},{stages:4},{roundSeconds:1}])a.throws(()=>createRoomSchema.parse({gameSlug:'ito',roomName:'Test',maxPlayers:3,settings:{ito}}));});
